### ISSUE TITLE
WLAN for OS mode visible, however not accessable

### ISSUE THREAD

**Issue by Trias544** [mc0110/inetbox2mqtt#78]
Hello,

I read from your project and wanted also to install in our RV. Unfortunatly I am only familiar with Arduino and not with Python.
Nevertheless I tried to programm with your description on an ESP32-WROOM-32 resp. ESP-WROOM-32UE (WOMOLIN).
It seems in the REPL the programming was successfully. Also the the ESP own WLAN is visible, however I get no connection.

May be you see on the protocoll why it is not working?

ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4728
load:0x40078000,len:14888
load:0x40080400,len:3368
entry 0x400805cc
INFO:__main__:release no: 2.6.5
HW:  RP2
INFO:connect:Detected micropython 1.23.0. 11014 on port: esp32
INFO:__main__:OS mode activated
INFO:connect:set ap to: 1
INFO:connect:AP enabled: 192.168.4.1
INFO:web_os_main:run lin:False inet:False webos:False naw:False file:False
INFO:web_os_main:run uart:1 tx:4 rx:5
INFO:web_os_main:HW-Check RP2 esp32
INFO:web_os:init
INFO:web_os_main:Start nanoweb server
INFO:web_os_main:Start OS command loop
Task exception wasn't retrieved
future: <Task> coro= <generator object 'run' at 3ffd9690>
Traceback (most recent call last):
  File "asyncio/core.py", line 1, in run_until_complete
  File "/lib/nanoweb.py", line 236, in run
  File "asyncio/stream.py", line 1, in start_server
OSError: -203
INFO:web_os_main:lin-loop is running

Best regards
Andreas

**Comment by mc0110** [comment]
Hi Andreas,

I'm not quite sure what you have done. The WOMOLIN installation only works on WOMOLIN-HW. You have set the HW platform:RP2, which looks as if you have not used the ready-made image for ESP32. Then the software is not executable. Please use the image and follow the instructions, pls.

Best regards
Magnus

**Comment by Trias544** [comment]
Hello Magnus,

thank you for your fast response. Unfortunately I was busy these days. Therefore I can answer first now.

First I installed micropython on the TI-CI-LIN Controller v2.1 by using the burnig tool of uPiCraft.
Then I tried to install inetbox2mqqt by using uPiCraft by using the sequence of your installation routine "Alternative 1: OTA-Installation with mip" as the esp32 has 16MB flash.

May be I have to use "Alternative 2: With esptool - only works with the ESP32". 
Has the memory size of 16MB flash anyway to be respected when using flash_womolin_inetbox2mqtt_v264_4M.bin.zip?

Best regards
Andreas

**Comment by Trias544** [comment]
Hello Magnus,

issue was solved by using bin file for WomoLin instead of ESP32.

Best regards
Andreas

**Comment by mc0110** [comment]
Great job - good news
